name: "Trigger Pega Pipeline"
description: 'Pega Javascript Action'
inputs:
  PEGA_DM_REST_URL:
    description: 'Pega Rest URL'
    required: true   

  PEGA_DM_CLIENT_ID:
    description: 'Pega Cleint Id'
    required: true    

  PEGA_DM_CLIENT_SECRET:
    description: 'Pega Client Secret'
    required: true

  JIRA_PEGA_APP_DATA_JSON:
    description: "Json file with Pega App Data"
    required: true

  PEGA_PIPELINE_MAPPING_JSON:
    description: "Json file with App to Pega Pipeline mapping"
    required: false

  PEGA_DEPLOYMENT_STATUS_JSON:
    description: "Json file with Pega deployment status"
    required: false

  JIRA_ISSUE_KEY:  
    description: 'Jira Issue Key'
    required: true 
  
runs:
  using: 'node16'
  main: 'dist/index.js'