name: 'AEM Pipeline'
description: 'AEM Pipeline - Trigger and Waitfor it to complete'
inputs:
  AEM_JSON_FILE_PATH: 
    description: 'Json file with required details'
    required: true 

  PRIVATE_KEY:
    description: "Private Key" 
    required: true 

  PROGRAMID: 
    description: 'Program Id'
    required: true

  PIPELINEID: 
    description: 'Pipeline Id'
    required: true   

  SHOULD_TRIGGER_PIPELINE:
    description: "Flag to trigger pipeline or not" 
    required: true
    type: boolean

  AEM_DEPLOYMENT_WAIT_TIME: 
    description: 'Wait time for pipeline to complete'
    required: true    

  IDLE_TIME_INTERVAL: 
    description: 'Idle time before gets pipeline status'
    required: true 

runs:
  using: 'node16'
  main: 'dist/index.js'