name: 'Boomi Deploy Packages'
description: 'Boomi Javascript Action'
inputs:
  BOOMI_REST_URL: 
    description: 'Boomi Rest URL'
    required: true   

  BOOMI_TFA_ACCOUNTID: 
    description: 'BOOMI_TFA_ACCOUNTID'
    required: true 

  BOOMI_REST_USERNAME:  
    description: 'Boomi Username'
    required: true    

  BOOMI_REST_PASSWORD: 
    description: 'Boomi Password/apikey'
    required: true 

  BOOMI_PACKAGES_JSON:
    description: 'Boomi Packages json'
    required: true 
    default: boomi-packages.json

  BOOMI_ENVIRONMENT: 
    description: 'BOOMI Environment'
    required: true

  BOOMI_ENVIRONMENT_ID: 
    description: 'BOOMI Environment Id'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'