name: 'Jira App List'
description: 'Jira App List'
inputs:
  JIRA_REST_API_URL:  
    description: 'Jira Rest URL'
    required: true   

  JIRA_ISSUE_KEY:  
    description: 'Jira Issue Key'
    required: true    

  JIRA_USERNAME: 
    description: 'Jira Username'
    required: true
    
  JIRA_API_KEY:
    description: "Jira API Key"
    required: true    

  JIRA_ISSUE_TRANSITION_TO_CODE:
    description: "Jira Issue Transition to the specified status"
    required: true  
    
runs:
  using: 'node16'
  main: 'dist/index.js'