name: 'Pega Trigger Pipeline'
description: 'Pega Javascript Action'
inputs:
  PEGA_DM_REST_URL:  # Pega Url
    description: 'Pega Rest URL'
    required: true   

  PEGA_DM_CLIENT_ID:  # Pega Url
    description: 'PegaCleinT_id'
    required: true    

  PEGA_DM_CLIENT_SECRET:  # Pega Url
    description: 'Pega Client Secret'
    required: true
    
  PEGA_PIEPLINE_ID:
    description: "Pipeline to trigger deployment"
    required: true    

  PEGA_PROD_NAME:
    description: "Product Rule Name to be deployed"
    required: true    

  PEGA_PROD_VERSION:
    description: "Product Rule Version to be deployed"
    required: true
    default: 01.01.01

  PEGA_DEPLOYMENT_WAIT_TIME:
    description: "Pega Deployment wait time"
    required: true
    default: "10"

  IDLE_TIME_INTERVAL:
    description: "Pega Deployment wait time"
    required: true
    default: "1"
    

runs:
  using: 'node16'
  main: 'dist/index.js'
