name: email-notification

on:  
  workflow_dispatch:
  push:
    paths:
      - 'custom-actions/email-notification/**'
      - '.github/workflows/email-notification.yml'

jobs:
  email-notification:
     runs-on: ubuntu-latest
     steps:   
     - name: Checkout
       uses: actions/checkout@v3
     - name: echo the wokflow url
       uses: ./custom-actions/email-notification
       with:
        STATUS: ${{ job.status }}
        SMTP_HOST: "smtp.office365.com"
        SMTP_PORT: "587"
        USERNAME: "asreddy@live.com"
        PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO: "asreddy@live.com"
