name: email-notification

on:  
  workflow_dispatch:
  push:
    paths:
      - 'custom-actions/email-notification/**'
      - '.github/workflows/email-notification.yml'

jobs:
  email-notification:
     runs-on: ubuntu-latest
     steps:   
     - name: Checkout
       uses: actions/checkout@v3
     - name: Create a file for attachment
       run: | 
        touch a.txt
        echo "Sample Data" >> a.txt
        mkdir test
        cd test
        touch b.txt
        echo "it is under test/b.txt" >> b.txt
     - name: Send email notiofication
       uses: ./custom-actions/email-notification
       with:
        STATUS: ${{ job.status }}
        SMTP_HOST: "smtp-mail.outlook.com"
        SMTP_PORT: "587"
        SMTP_USERNAME: "asreddy@live.com"
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO: "asreddy@live.com"
        CC: "sudarsana.ala@gmail.com"
        ATTACHMENTS: "a.txt;test/b.txt;c.txt"
