name: node-practice-pipeline

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "DRY_RUN:Flag to set dry run or actual run"
        type: boolean
        required: false
      INPUT_REPOS:
        description: "INPUT_REPOS: Comma(,) separated list of targeted repos or 'ALL' for all repos in the org"
        type: string
        required: true
      DAYS_OLDER_THAN:
        description: "DAYS_OLDER_THAN: The job will delete the artifacts older than the set valus of this input. Default is 30 days."
        type: string
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: npm install
        run: |
          cd custom-actions/node-practice
          npm install

      - name: run job
        run: |
          cd custom-actions/node-practice
          npm run start
        shell: bash
        env:
          DRY_RUN: ${{ inputs.DRY_RUN }}
          INPUT_REPOS: ${{ inputs.INPUT_REPOS }}
          TOKEN: ${{ secrets.TOKEN }}