name: report-annotations-test

on:  
  workflow_dispatch:  
  push:
    paths:
      - 'custom-actions/report-annotations/**'
      - '.github/workflows/report-annotations-test.yml' 


jobs:
  report-annotations-test:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add annotations to report
        uses: ./custom-actions/report-annotations
        with:
          FILE_NAME: "${{ github.workspace }}/test.txt"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: annotations
          path: "${{ github.workspace }}/test.txt"

  download-and-print-test:
    runs-on: ubuntu-latest
    needs: report-annotations-test
    if: always()
    steps:   
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download test file
        uses: actions/download-artifact@v3
        with:
          name: annotations
          
      - name: Print the contents
        run: |
          data=$(cat test.txt)
          echo "data: $data"
          echo "ANNOTATIONS=$data" >> "GITHUB_ENV"
          echo ${{ env.ANNOTATIONS }}

      - name: Send Email Notification
        if: always()
        uses: ./custom-actions/email-notification
        with:
          STATUS: "${{ job.status }} - ${{ env.ANNOTATIONS }}"
          SMTP_HOST: "smtp-mail.outlook.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: "asreddy@live.com"
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO: "asreddy@live.com"
          CC: "asreddy@live.com" 


      

