name: report-annotations-test

on:  
  workflow_dispatch:  

jobs:
  report-annotations-test:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo the wokflow url
        uses: ./custom-actions/report-annotations
        with:
          FILE_NAME: "${{ github.workspace }}/test.txt"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: annotations
          path: test.txt

  download-and-print-test:
    runs-on: ubuntu-latest
    steps:   
      - name: Download test file
        uses: actions/download-artifact@v3
        with:
          name: annotations
          
      - name: Print the contents
        run: |
          cat test.txt

