name: trigger-pega-pipelines

on: [workflow_dispatch]

jobs:
  trigger-pega-pipelines:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Jira Desciption Data
        id: jiraData
        uses: ./custom-actions/jira-description-data
        with:
          JIRA_REST_API_URL: ${{secrets.JIRA_REST_API_URL}}
          JIRA_ISSUE_KEY: "PEG-8"
          JIRA_USERNAME: ${{secrets.JIRA_USERNAME}}
          JIRA_API_KEY: ${{secrets.JIRA_API_KEY}}
          JIRA_APP_JSON_FILE: "jira-pega-apps.json" 

      - name: Upload jira app json file
        uses: actions/upload-artifact@v3
        with:         
          name: jira-pega-apps.json
          # A file, directory or wildcard pattern that describes what to upload
          path: jira-pega-apps.json

      - name: Trigger Pega Piplines
        uses: ./custom-actions/trigger-pega-pipelines
        with:
          PEGA_DM_REST_URL: ${{ secrets.PEGA_DM_REST_URL }}
          PEGA_DM_CLIENT_ID: ${{ secrets.PEGA_DM_CLIENT_ID }}
          PEGA_DM_CLIENT_SECRET: ${{ secrets.PEGA_DM_CLIENT_SECRET }}
          JIRA_PEGA_APP_DATA_JSON: "jira-pega-apps.json"
          PEGA_PIPELINE_MAPPING_JSON: "pega-pipilne-mappings.json"

              