name: workflow-conclusion

on:  
  push:
    paths:
      - 'custom-actions/workflow-conclusion/**'
      - '.github/workflows/workflow-conclusion.yml'
  workflow_dispatch:


jobs:
  Pass-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Print job status
      run: |
        echo ${{ job.status }}
       
        
  Fail-Job:
    runs-on: ubuntu-latest   
    steps:
    - name: Error Step
      run: |
         error_message="This is an error message"
         echo "::error:: $error_message"
         echo "::set-ouput name=error_message::$error_message"
         exit 1
    - name: Print job status
      if: always()
      run:
        echo ${{ job.status }}

  workflow-status:
     runs-on: ubuntu-latest
     needs: [Pass-Job, Fail-Job]
     if: always()
     steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: List Jobs of the current workflow
       uses: ./custom-actions/workflow-conclusion     
