name: workflow-conclusion

on:  
  push:
    paths:
      - 'custom-actions/workflow-conclusion/**'
      - '.github/workflows/workflow-conclusion.yml'
  workflow_dispatch:


jobs:
  Pass-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Print job status
      run: |
        echo ${{ job.status }}
       
        
  Fail-Job:
    runs-on: ubuntu-latest
    outputs:
      error_message: ${{ steps.error_step.outputs.error_message }}   
    steps:
    - name: Error Step
      id: error_step
      run: |
         error_message="This is an error message"
         echo "::error:: $error_message"
         echo "::set-output name=error_message::$error_message"
         exit 1
    - name: Print job status
      if: always()
      run:
        echo ${{ job.status }}

  workflow-status:
     runs-on: ubuntu-latest
     needs: [Pass-Job, Fail-Job]
     if: always()
     steps:
#      - name: Echo the error message
#        run: |
#           echo ${{ needs.Fail-Job.outputs.error_message }} >> $GITHUB_STEP_SUMMARY
     - name: Checkout
       uses: actions/checkout@v3
     - name: List Jobs of the current workflow
       if: always()
       uses: ./custom-actions/workflow-conclusion
       with:
        TOKEN: ${{ github.token }}
